import { NextApiRequest, NextApiResponse } from 'next'

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const movies = [
    { title: 'The Shawshank Redemption', year: 1994 },
    { title: 'The Godfather', year: 1972 },
    { title: 'The Dark Knight', year: 2008 },
    { title: 'The Godfather Part II', year: 1974 },
    { title: '12 Angry Men', year: 1957 },
    { title: "Schindler's List", year: 1993 },
    { title: 'The Lord of the Rings: The Return of the King', year: 2003 },
    { title: 'Pulp Fiction', year: 1994 },
    { title: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001 },
    { title: 'The Good, the Bad and the Ugly', year: 1966 },
    { title: 'Forrest Gump', year: 1994 },
    { title: 'Fight Club', year: 1999 },
    { title: 'The Lord of the Rings: The Two Towers', year: 2002 },
    { title: 'Inception', year: 2010 },
    { title: 'Star Wars: Episode V - The Empire Strikes Back', year: 1980 },
    { title: 'The Matrix', year: 1999 },
    { title: 'Goodfellas', year: 1990 },
    { title: "One Flew Over the Cuckoo's Nest", year: 1975 },
    { title: 'Se7en', year: 1995 },
    { title: 'Seven Samurai', year: 1954 },
    { title: "It's a Wonderful Life", year: 1946 },
    { title: 'The Silence of the Lambs', year: 1991 },
    { title: 'Saving Private Ryan', year: 1998 },
    { title: 'City of God', year: 2002 },
    { title: 'Interstellar', year: 2014 },
    { title: 'Life Is Beautiful', year: 1997 },
    { title: 'The Green Mile', year: 1999 },
    { title: 'Star Wars: Episode IV - A New Hope', year: 1977 },
    { title: 'Terminator 2: Judgment Day', year: 1991 },
    { title: 'Back to the Future', year: 1985 },
    { title: 'Spirited Away', year: 2001 },
    { title: 'The Pianist', year: 2002 },
    { title: 'Psycho', year: 1960 },
    { title: 'Parasite', year: 2019 },
    { title: 'L\u00e9on: The Professional', year: 1994 },
    { title: 'The Lion King', year: 1994 },
    { title: 'Gladiator', year: 2000 },
    { title: 'American History X', year: 1998 },
    { title: 'The Departed', year: 2006 },
    { title: 'The Usual Suspects', year: 1995 },
    { title: 'The Prestige', year: 2006 },
    { title: 'Whiplash', year: 2014 },
    { title: 'Casablanca', year: 1942 },
    { title: 'Harakiri', year: 1962 },
    { title: 'Grave of the Fireflies', year: 1988 },
    { title: 'The Intouchables', year: 2011 },
    { title: 'Modern Times', year: 1936 },
    { title: 'Once Upon a Time in the West', year: 1968 },
    { title: 'Rear Window', year: 1954 },
    { title: 'Cinema Paradiso', year: 1988 },
    { title: 'Alien', year: 1979 },
    { title: 'City Lights', year: 1931 },
    { title: 'Apocalypse Now', year: 1979 },
    { title: 'Memento', year: 2000 },
    { title: 'Django Unchained', year: 2012 },
    { title: 'Indiana Jones and the Raiders of the Lost Ark', year: 1981 },
    { title: 'WALL\u00b7E', year: 2008 },
    { title: 'The Lives of Others', year: 2006 },
    { title: 'Sunset Blvd.', year: 1950 },
    { title: 'Paths of Glory', year: 1957 },
    { title: 'The Shining', year: 1980 },
    { title: 'The Great Dictator', year: 1940 },
    { title: 'Avengers: Infinity War', year: 2018 },
    { title: 'Witness for the Prosecution', year: 1957 },
    { title: 'Aliens', year: 1986 },
    { title: 'Spider-Man: Into the Spider-Verse', year: 2018 },
    { title: 'American Beauty', year: 1999 },
    {
      title:
        'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
      year: 1964,
    },
    { title: 'The Dark Knight Rises', year: 2012 },
    { title: 'Oldboy', year: 2003 },
    { title: 'Inglourious Basterds', year: 2009 },
    { title: 'Amadeus', year: 1984 },
    { title: 'Coco', year: 2017 },
    { title: 'Toy Story', year: 1995 },
    { title: 'Joker', year: 2019 },
    { title: 'Braveheart', year: 1995 },
    { title: 'The Boat', year: 1981 },
    { title: 'Avengers: Endgame', year: 2019 },
    { title: 'Princess Mononoke', year: 1997 },
    { title: 'Once Upon a Time in America', year: 1984 },
    { title: 'Good Will Hunting', year: 1997 },
    { title: 'Your Name.', year: 2016 },
    { title: "Singin' in the Rain", year: 1952 },
    { title: '3 Idiots', year: 2009 },
    { title: 'Requiem for a Dream', year: 2000 },
    { title: 'High and Low', year: 1963 },
    { title: 'Toy Story 3', year: 2010 },
    { title: 'Capernaum', year: 2018 },
    { title: 'Star Wars: Episode VI - Return of the Jedi', year: 1983 },
    { title: 'Eternal Sunshine of the Spotless Mind', year: 2004 },
    { title: '2001: A Space Odyssey', year: 1968 },
    { title: 'Reservoir Dogs', year: 1992 },
    { title: 'Come and See', year: 1985 },
    { title: 'The Hunt', year: 2012 },
    { title: 'Citizen Kane', year: 1941 },
    { title: 'M', year: 1931 },
    { title: 'Lawrence of Arabia', year: 1962 },
    { title: 'North by Northwest', year: 1959 },
    { title: 'Ikiru', year: 1952 },
    { title: 'Vertigo', year: 1958 },
    { title: 'The Apartment', year: 1960 },
    { title: 'Am\u00e9lie', year: 2001 },
    { title: 'A Clockwork Orange', year: 1971 },
    { title: 'Double Indemnity', year: 1944 },
    { title: 'Full Metal Jacket', year: 1987 },
    { title: 'Scarface', year: 1983 },
    { title: 'Hamilton', year: 2020 },
    { title: 'Top Gun: Maverick', year: 2022 },
    { title: 'Incendies', year: 2010 },
    { title: 'To Kill a Mockingbird', year: 1962 },
    { title: 'Heat', year: 1995 },
    { title: 'The Sting', year: 1973 },
    { title: 'Up', year: 2009 },
    { title: 'A Separation', year: 2011 },
    { title: 'Metropolis', year: 1927 },
    { title: 'Taxi Driver', year: 1976 },
    { title: 'L.A. Confidential', year: 1997 },
    { title: 'Die Hard', year: 1988 },
    { title: 'Snatch', year: 2000 },
    { title: 'Indiana Jones and the Last Crusade', year: 1989 },
    { title: 'Bicycle Thieves', year: 1948 },
    { title: 'Like Stars on Earth', year: 2007 },
    { title: '1917', year: 2019 },
    { title: 'Downfall', year: 2004 },
    { title: 'Dangal', year: 2016 },
    { title: 'For a Few Dollars More', year: 1965 },
    { title: 'Batman Begins', year: 2005 },
    { title: 'The Kid', year: 1921 },
    { title: 'Some Like It Hot', year: 1959 },
    { title: 'The Father', year: 2020 },
    { title: 'All About Eve', year: 1950 },
    { title: 'The Wolf of Wall Street', year: 2013 },
    { title: 'Green Book', year: 2018 },
    { title: 'Judgment at Nuremberg', year: 1961 },
    { title: 'Casino', year: 1995 },
    { title: 'Ran', year: 1985 },
    { title: "Pan's Labyrinth", year: 2006 },
    { title: 'The Truman Show', year: 1998 },
    { title: 'There Will Be Blood', year: 2007 },
    { title: 'Unforgiven', year: 1992 },
    { title: 'The Sixth Sense', year: 1999 },
    { title: 'Shutter Island', year: 2010 },
    { title: 'A Beautiful Mind', year: 2001 },
    { title: 'Jurassic Park', year: 1993 },
    { title: 'Yojimbo', year: 1961 },
    { title: 'The Treasure of the Sierra Madre', year: 1948 },
    { title: 'Monty Python and the Holy Grail', year: 1975 },
    { title: 'The Great Escape', year: 1963 },
    { title: 'No Country for Old Men', year: 2007 },
    { title: 'Kill Bill: Vol. 1', year: 2003 },
    { title: 'Rashomon', year: 1950 },
    { title: 'Spider-Man: No Way Home', year: 2021 },
    { title: 'The Thing', year: 1982 },
    { title: 'Finding Nemo', year: 2003 },
    { title: 'The Elephant Man', year: 1980 },
    { title: 'Chinatown', year: 1974 },
    { title: 'Raging Bull', year: 1980 },
    { title: 'V for Vendetta', year: 2005 },
    { title: 'Gone with the Wind', year: 1939 },
    { title: 'Lock, Stock and Two Smoking Barrels', year: 1998 },
    { title: 'Inside Out', year: 2015 },
    { title: 'Dial M for Murder', year: 1954 },
    { title: 'The Secret in Their Eyes', year: 2009 },
    { title: "Howl's Moving Castle", year: 2004 },
    { title: 'Three Billboards Outside Ebbing, Missouri', year: 2017 },
    { title: 'The Bridge on the River Kwai', year: 1957 },
    { title: 'Trainspotting', year: 1996 },
    { title: 'Prisoners', year: 2013 },
    { title: 'Warrior', year: 2011 },
    { title: 'Fargo', year: 1996 },
    { title: 'Gran Torino', year: 2008 },
    { title: 'My Neighbor Totoro', year: 1988 },
    { title: 'Catch Me If You Can', year: 2002 },
    { title: 'Million Dollar Baby', year: 2004 },
    { title: 'Children of Heaven', year: 1997 },
    { title: 'Blade Runner', year: 1982 },
    { title: 'The Gold Rush', year: 1925 },
    { title: 'Before Sunrise', year: 1995 },
    { title: 'Klaus', year: 2019 },
    { title: '12 Years a Slave', year: 2013 },
    { title: 'Harry Potter and the Deathly Hallows: Part 2', year: 2011 },
    { title: 'On the Waterfront', year: 1954 },
    { title: 'Ben-Hur', year: 1959 },
    { title: 'Gone Girl', year: 2014 },
    { title: 'The Grand Budapest Hotel', year: 2014 },
    { title: 'Wild Strawberries', year: 1957 },
    { title: 'The General', year: 1926 },
    { title: 'The Third Man', year: 1949 },
    { title: 'In the Name of the Father', year: 1993 },
    { title: 'The Deer Hunter', year: 1978 },
    { title: 'Barry Lyndon', year: 1975 },
    { title: 'Hacksaw Ridge', year: 2016 },
    { title: 'The Wages of Fear', year: 1953 },
    { title: 'Memories of Murder', year: 2003 },
    { title: 'Sherlock Jr.', year: 1924 },
    { title: 'Wild Tales', year: 2014 },
    { title: 'Mr. Smith Goes to Washington', year: 1939 },
    { title: 'Mad Max: Fury Road', year: 2015 },
    { title: 'The Seventh Seal', year: 1957 },
    { title: 'Mary and Max', year: 2009 },
    { title: 'How to Train Your Dragon', year: 2010 },
    { title: 'Room', year: 2015 },
    { title: 'Monsters, Inc.', year: 2001 },
    { title: 'Jaws', year: 1975 },
    { title: 'Dead Poets Society', year: 1989 },
    { title: 'The Big Lebowski', year: 1998 },
    { title: 'Tokyo Story', year: 1953 },
    { title: 'The Passion of Joan of Arc', year: 1928 },
    { title: 'Hotel Rwanda', year: 2004 },
    { title: 'Ford v Ferrari', year: 2019 },
    { title: 'Rocky', year: 1976 },
    { title: 'Platoon', year: 1986 },
    { title: 'Ratatouille', year: 2007 },
    { title: 'Spotlight', year: 2015 },
    { title: 'The Terminator', year: 1984 },
    { title: 'Logan', year: 2017 },
    { title: 'Stand by Me', year: 1986 },
    { title: 'Rush', year: 2013 },
    { title: 'Network', year: 1976 },
    { title: 'Before Sunset', year: 2004 },
    { title: 'Into the Wild', year: 2007 },
    { title: 'The Wizard of Oz', year: 1939 },
    { title: 'Pather Panchali', year: 1955 },
    { title: 'Groundhog Day', year: 1993 },
    { title: 'The Best Years of Our Lives', year: 1946 },
    { title: 'The Exorcist', year: 1973 },
    { title: 'To Be or Not to Be', year: 1942 },
    { title: 'The Incredibles', year: 2004 },
    { title: 'La haine', year: 1995 },
    {
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
      year: 2003,
    },
    { title: 'The Battle of Algiers', year: 1966 },
    { title: 'Jai Bhim', year: 2021 },
    { title: 'The Grapes of Wrath', year: 1940 },
    { title: "Hachi: A Dog's Tale", year: 2009 },
    { title: 'My Father and My Son', year: 2005 },
    { title: 'Rebecca', year: 1940 },
    { title: 'Amores Perros', year: 2000 },
    { title: 'Cool Hand Luke', year: 1967 },
    { title: 'The Handmaiden', year: 2016 },
    { title: 'The 400 Blows', year: 1959 },
    { title: 'The Sound of Music', year: 1965 },
    { title: 'It Happened One Night', year: 1934 },
    { title: 'Persona', year: 1966 },
    { title: 'Life of Brian', year: 1979 },
    { title: 'The Iron Giant', year: 1999 },
    { title: 'Dersu Uzala', year: 1975 },
    { title: 'The Help', year: 2011 },
    { title: 'Aladdin', year: 1992 },
    { title: 'Gandhi', year: 1982 },
    { title: 'Dances with Wolves', year: 1990 },
  ]
  res.status(200).json(movies)
}
